### ISSUE TITLE
Bad documentation

### ISSUE THREAD

**Issue by neoighodaro** [aaronsaray/madmimi-api-php#5]
You should improve the documentation. It looks very lazy, shame because its such a great library.

**Comment by aaronsaray** [comment]
@neoighodaro thanks for your feedback

Can you tell me which particular section you're referring to? In the main readme, there are a number of links to the doc sections - which should give you all the documentation you need.  Perhaps I'm missing something?  Can you give an example?

**Comment by aaronsaray** [comment]
It just occurred to me that you might be referring to the documentation on the madmimi.com website?  If so, I'm not affiliated with that company.  I just needed to use the API, so I created this PHP library to do it easier and normalize the process.  

Again, for reference, this API is documented using the README.md file - otherwise here is a link to the docs as well:  https://github.com/aaronsaray/madmimi-api-php/tree/master/docs
